# Generated by Django 4.1.4 on 2022-12-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=150)),
                ('moviedisc', models.TextField()),
                ('Releaseyear', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
